name: GCC 12 Build
on:
    push:
jobs:
    build-project:
        strategy:
            matrix:
                type: [ Debug, Release ]
                os: [ ubuntu-latest ]

        name: Build Project
        runs-on: ${{ matrix.os }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v4.1.1

            -   uses: awalsh128/cache-apt-pkgs-action@latest
                with:
                    packages: qemu-system-arm g++-12-aarch64-linux-gnu gcc-12-aarch64-linux-gnu mtools
                    version: 1.0

            -   name: Configure Project
                run: |
                    cmake -B ${{github.workspace}}/build \
                        --toolchain=cmake/GCCToolchain.cmake \
                        -DCMAKE_BUILD_TYPE=${{matrix.type}} \
                        -DGCC_PREFIX=aarch64-linux-gnu- \
                        -DGCC_SUFFIX=-12

            -   name: Build Project
                run: make -j -C build VERBOSE=1

            # - name: Test Project
            #  runs: ctest --test-dir build
